name: Auto Update TryHackMe Progress

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests matplotlib

      - name: Run script
        env:
          THM_COOKIE: ${{ secrets.THM_COOKIE }}
        run: python thmprogress.py

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add *.png *.json
          git commit -m "Auto-update: THM progress charts" || echo "No changes"
          git push
